// 可选浏览器回归测试：PLAYWRIGHT_MODULE 与 CHROMIUM_EXECUTABLE 指向已有安装。
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_EXECUTABLE, headless: true });
  try {
    const context = await browser.newContext({ viewport: { width: 1000, height: 850 } });
    await context.addCookies([{ name: 'vocat_csrf', value: 'test-csrf', url: 'http://vocat.test' }]);
    const page = await context.newPage();
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    let nodeLink = '', failConnection = false, probeRequest;
    let nodes = [], upstreams = [], failSave = false, failDelete = false, writes = 0, nodePassword = "";
    const item = { id: 'xray-manager-0123456789abcdef', name: '<img src=x onerror=alert(1)>', protocol: 'vless', addr: '127.0.0.1:12345', running: true, enabled: true };
    await page.route('http://vocat.test/**', async route => {
      const req = route.request(), url = new URL(req.url()), method = req.method();
      const send = (data, status = 200) => route.fulfill({ status, json: status === 200 ? { data } : { error: { message: data } } });
      if (url.pathname === '/host') return route.fulfill({ contentType: 'text/html', body: '<!doctype html><html class="dark"><body><iframe title="Xray管理" src="/plugin-assets/xray-manager/web/panel.html" sandbox="allow-scripts allow-forms allow-same-origin" width="100%" height="800"></iframe></body></html>' });
      if (url.pathname.startsWith('/plugin-assets/')) {
        const name = path.basename(url.pathname);
        return route.fulfill({ body: fs.readFileSync(path.join(__dirname, 'web', name)), contentType: name.endsWith('.html') ? 'text/html' : name.endsWith('.js') ? 'text/javascript' : 'text/css', headers: { 'Content-Security-Policy': "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'" } });
      }
      if (url.pathname.startsWith('/api/extensions/')) assert.ok(url.pathname.startsWith('/api/extensions/xray-manager/backend/'));
      if (method !== 'GET') {
        assert.equal(req.headers()['x-csrf-token'], 'test-csrf');
        assert.equal(req.headers()['content-type'], 'application/json');
      }
      if (url.pathname.startsWith('/api/upstream-proxies')) {
        if (method === 'GET') return send(upstreams.map(value => ({ ...value, password: value.password ? '********' : '' })));
        writes++;
        if (failSave && ['POST', 'PUT'].includes(method)) return send('模拟宿主保存失败', 500);
        if (method === 'POST' || method === 'PUT') upstreams = [req.postDataJSON()];
        if (method === 'PATCH') upstreams[0].enabled = false;
        if (method === 'DELETE') upstreams = [];
        return send({});
      }
      if (url.pathname.endsWith('/nodes') && method === 'GET') return send(nodes);
      if (url.pathname.endsWith('/nodes') && method === 'POST') {
        if (req.postDataJSON().link === 'invalid') return send('不支持的链接', 400);
        assert.equal(typeof req.postDataJSON().port, 'number');
        if (!nodes.length) {
          const settings = req.postDataJSON();
          nodeLink = settings.link;
          nodePassword = settings.auth_enabled ? settings.password : '';
          nodes = [{ ...item, inbound_mode: settings.inbound_mode || 'mixed', udp_enabled: settings.inbound_mode !== 'http' && settings.udp_enabled !== false, addr: `127.0.0.1:${settings.port || 12345}`, allow_lan: !!settings.allow_lan, auth_enabled: !!settings.auth_enabled, username: settings.auth_enabled ? settings.username : '', password_set: !!nodePassword }];
        }
        return send(nodes[0]);
      }
      if (url.pathname.endsWith('/settings') && method === 'PUT') {
        const port = req.postDataJSON().port;
        if (port === 54321) return send('本地 TCP/UDP 端口已占用', 400);
        nodes[0].previous_addrs = [...(nodes[0].previous_addrs || []), nodes[0].addr];
        nodes[0].addr = `127.0.0.1:${port}`;
        const settings = req.postDataJSON();
        if (nodes[0].username) nodes[0].previous_usernames = [...(nodes[0].previous_usernames || []), nodes[0].username];
        nodes[0].inbound_mode = settings.inbound_mode;
        nodes[0].udp_enabled = settings.inbound_mode !== 'http' && settings.udp_enabled;
        nodes[0].allow_lan = settings.allow_lan;
        nodes[0].auth_enabled = settings.auth_enabled;
        nodes[0].username = settings.auth_enabled ? settings.username : '';
        if (!settings.auth_enabled) nodePassword = '';
        else if (Object.hasOwn(settings, 'password')) nodePassword = settings.password;
        nodes[0].password_set = !!nodePassword;
        return send(nodes[0]);
      }
      if (url.pathname.endsWith('/connection')) {
        if (method === 'GET') return send({link:nodeLink});
        if (failConnection) return send('模拟参数保存失败', 400);
        nodeLink = req.postDataJSON().link; return send(nodes[0]);
      }
      if (url.pathname.endsWith('/probe')) { probeRequest = req.postDataJSON(); return send({ok:true,status_code:204,latency_ms:87,error:''}); }
      if (url.pathname.endsWith('/export')) return send({ id: item.id, name: '测试节点', addr: nodes[0].addr, username: nodes[0].username || '', password: nodePassword, enabled: true });
      if (url.pathname.endsWith('/start')) { nodes[0].running = nodes[0].enabled = true; return send(nodes[0]); }
      if (url.pathname.endsWith('/stop')) { nodes[0].running = nodes[0].enabled = false; return send(nodes[0]); }
      if (method === 'DELETE') {
        if (failDelete) return send('模拟磁盘写入失败', 400);
        nodes = []; return send({});
      }
      throw new Error('unexpected route ' + method + ' ' + url.pathname);
    });
    await page.goto('http://vocat.test/plugin-assets/xray-manager/web/panel.html');
    await page.waitForFunction(() => document.querySelector('#load-state').textContent.includes('还没有'));
    const click = async name => { await page.getByRole('button', { name, exact: true }).click(); await page.waitForFunction(() => !document.querySelector('#import-button').disabled); };
    await click('新增节点');
    assert.equal(await page.locator('#import-dialog').evaluate(el => el.open), true);
    await page.locator('#link').fill('invalid');
    await click('导入并推送到 VoCat');
    assert.equal(await page.locator('#link').inputValue(), 'invalid');
    assert.match(await page.locator('#notice').innerText(), /不支持/);
    failSave = true;
    await page.locator('#import-port').fill('12345');
    await page.locator('#link').fill('vless://test-node');
    await click('导入并推送到 VoCat');
    assert.equal(await page.locator('#link').inputValue(), 'vless://test-node');
    assert.equal(await page.locator('.node').count(), 1);
    assert.match(await page.locator('#notice').innerText(), /节点.*已保存/);
    assert.equal(await page.locator('.node img').count(), 0);
    assert.match(await page.locator('#form-notice').innerText(), /节点.*已保存/);
    await click('关闭');
    await click('新增节点');
    assert.equal(await page.locator('#link').inputValue(), 'vless://test-node');
    await click('关闭');
    failSave = false;
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams.length, 1);
    assert.equal(upstreams[0].addr, item.addr);
    assert.equal(upstreams[0].username, '');
    assert.equal(upstreams[0].password, '');
    upstreams[0].username = 'foreign-owner';
    const before = writes;
    await click('停止');
    assert.equal(writes, before);
    assert.equal(nodes[0].running, true);
    assert.match(await page.locator('#notice').innerText(), /同 ID/);
    await click('删除'); await click('确认删除');
    assert.equal(writes, before);
    assert.equal(nodes.length, 1);
    upstreams[0].username = '';
    await click('停止');
    assert.equal(nodes[0].running, false);
    assert.equal(upstreams[0].enabled, false);
    await click('启动并推送');
    assert.equal(nodes[0].running, true);
    assert.equal(upstreams[0].enabled, true);
    await click('连接设置');
    assert.equal(await page.locator('#node-port').inputValue(), '12345');
    await page.locator('#node-port').fill('54321');
    await click('保存设置');
    assert.equal(nodes[0].addr, '127.0.0.1:12345');
    assert.equal(await page.locator('#node-port').inputValue(), '54321');
    assert.match(await page.locator('#port-notice').innerText(), /占用/);
    await page.locator('#node-port').fill('12346');
    await click('保存设置');
    assert.equal(await page.locator('#port-dialog').evaluate(el => el.open), false);
    assert.equal(nodes[0].addr, '127.0.0.1:12346');
    assert.equal(upstreams[0].addr, '127.0.0.1:12345');
    assert.match(await page.locator('.push-state').innerText(), /地址不一致/);
    failSave = true;
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].addr, '127.0.0.1:12345');
    failSave = false;
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams.length, 1);
    assert.equal(upstreams[0].id, item.id);
    assert.equal(upstreams[0].addr, '127.0.0.1:12346');
    await click('连接设置');
    await page.locator('#node-lan').check();
    await page.locator('#node-auth').check();
    await page.locator('#node-username').fill('alice');
    assert.equal(await page.locator('#port-form').evaluate(el => el.checkValidity()), false);
    await page.locator('#node-password').fill('test-local-password');
    await click('保存设置');
    assert.equal(nodes[0].allow_lan, true);
    assert.equal(nodes[0].auth_enabled, true);
    assert.equal(Object.hasOwn(nodes[0], 'password'), false);
    assert.match((await page.locator('.access-mode').allTextContents()).join(' '), /局域网.*账号认证/);
    failSave = true;
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].username, '');
    failSave = false;
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].username, 'alice');
    assert.equal(upstreams[0].password, 'test-local-password');
    await click('连接设置');
    assert.equal(await page.locator('#node-password').inputValue(), '');
    assert.equal(await page.locator('#node-username').inputValue(), 'alice');
    await page.locator('#node-username').fill('bob');
    await click('保存设置');
    assert.equal(nodePassword, 'test-local-password');
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].username, 'bob');
    assert.equal(upstreams[0].password, 'test-local-password');
    await click('连接设置');
    await page.locator('#node-password').fill('replacement-password');
    await click('保存设置');
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].password, 'replacement-password');
    await click('连接设置');
    await page.locator('#node-auth').uncheck();
    await page.locator('#node-lan').uncheck();
    await click('保存设置');
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].username, '');
    assert.equal(upstreams[0].password, '');
    assert.match((await page.locator('.access-mode').allTextContents()).join(' '), /仅本机.*无认证/);
    assert.equal(await page.locator('main > header h1, #node-count, details.help').count(), 0);
    assert.equal(await page.locator('th:last-child').evaluate(el => getComputedStyle(el).textAlign), 'left');
    assert.equal(await page.locator('.actions').evaluate(el => getComputedStyle(el).justifyContent), 'flex-start');
    // 混合/HTTP切换、UDP选项与宿主禁用必须由真实用户入口完成。
    await click('连接设置');
    await page.locator('#node-mode').selectOption('http');
    assert.equal(await page.locator('#node-udp').isDisabled(), true);
    await click('保存设置');
    assert.equal(nodes[0].inbound_mode, 'http');
    assert.equal(upstreams[0].enabled, false);
    assert.equal(await page.getByRole('button', {name:'推送到 VoCat 代理管理', exact:true}).count(), 0);
    await click('检测');
    await page.locator('#probe-target').selectOption('cloudflare');
    await page.locator('#probe-timeout').fill('6');
    await click('开始检测');
    assert.equal(probeRequest.target, 'cloudflare');
    assert.equal(Object.hasOwn(probeRequest, 'url'), false);
    assert.equal(probeRequest.timeout_seconds, 6);
    assert.match(await page.locator('#probe-result').innerText(), /代理访问成功.*87 ms.*HTTP 204/);
    await page.locator('#cancel-probe').click();
    await click('连接设置');
    await page.locator('#node-mode').selectOption('mixed');
    await page.locator('#node-udp').uncheck();
    await click('保存设置');
    assert.equal(nodes[0].udp_enabled, false);
    await click('推送到 VoCat 代理管理');
    assert.equal(upstreams[0].enabled, true);
    // 远端参数失败保留输入；成功回读，身份与端口保持不变。
    const previousID = nodes[0].id, previousAddr = nodes[0].addr;
    await click('节点参数');
    await page.locator('#connection-link').fill('vless://6ba7b810-9dad-41d1-80b4-00c04fd430c8@example.com:443?type=tcp&security=tls#test');
    await page.locator('#connection-parameters summary').click();
    await page.locator('#connection-parameters-type').selectOption('grpc');
    await page.locator('#connection-parameters-serviceName').fill('service-name');
    assert.match(await page.locator('#connection-link').inputValue(), /type=grpc/);
    assert.match(await page.locator('#connection-link').inputValue(), /serviceName=service-name/);
    failConnection = true;
    await click('保存节点参数');
    assert.equal(await page.locator('#connection-dialog').evaluate(el => el.open), true);
    assert.match(await page.locator('#connection-notice').innerText(), /模拟参数保存失败/);
    failConnection = false;
    await click('保存节点参数');
    assert.equal(nodes[0].id, previousID); assert.equal(nodes[0].addr, previousAddr);
    assert.equal(await page.locator('#connection-link').inputValue(), '');
    await click('节点参数');
    await page.locator('#connection-parameters summary').click();
    assert.match(await page.locator('#connection-link').inputValue(), /serviceName=service-name/);
    await page.locator('#cancel-connection').click();
    // KCP头部/seed和XHTTP独立下载编辑必须写回同一份链接。
    await click('节点参数');
    await page.locator('#connection-link').fill('vless://6ba7b810-9dad-41d1-80b4-00c04fd430c8@example.com:443?type=kcp#kcp');
    await page.locator('#connection-parameters').locator('details').evaluate(el => {el.open=true;});
    await page.locator('#connection-parameters-headerType').selectOption('wireguard');
    await page.locator('#connection-parameters-seed').fill('seed & 中文');
    const kcpQuery = new URL(await page.locator('#connection-link').inputValue()).searchParams;
    assert.equal(kcpQuery.get('headerType'), 'wireguard'); assert.equal(kcpQuery.get('seed'), 'seed & 中文');
    await click('保存节点参数');
    await click('节点参数');
    const extraFromLink = { noGRPCHeader:true, downloadSettings:{address:'download.example.com',port:443,network:'xhttp',security:'tls',tlsSettings:{serverName:'download.example.com'},xhttpSettings:{path:'/download'}} };
    const xhttpURL = new URL('vless://6ba7b810-9dad-41d1-80b4-00c04fd430c8@example.com:80?type=xhttp&mode=packet-up#split');
    xhttpURL.searchParams.set('extra', JSON.stringify(extraFromLink));
    await page.locator('#connection-link').fill(xhttpURL.href);
    assert.deepEqual(JSON.parse(await page.locator('#connection-parameters-downloadSettings').inputValue()), extraFromLink.downloadSettings);
    assert.deepEqual(JSON.parse(await page.locator('#connection-parameters-extra').inputValue()), {noGRPCHeader:true});
    await page.locator('#connection-parameters-downloadSettings').fill('{broken');
    assert.equal(await page.locator('#connection-form').evaluate(el => el.checkValidity()), false);
    await page.locator('#connection-parameters-extra').fill('{"noSSEHeader":true}');
    assert.equal(await page.locator('#connection-parameters-downloadSettings').inputValue(), '{broken');
    const newDownload = {...extraFromLink.downloadSettings,port:8443};
    await page.locator('#connection-parameters-downloadSettings').fill(JSON.stringify(newDownload));
    const combined = JSON.parse(new URL(await page.locator('#connection-link').inputValue()).searchParams.get('extra'));
    assert.deepEqual(combined, {noSSEHeader:true,downloadSettings:newDownload});
    assert.equal(await page.locator('#connection-form').evaluate(el => el.checkValidity()), true);
    failConnection = true; await click('保存节点参数');
    assert.deepEqual(JSON.parse(await page.locator('#connection-parameters-downloadSettings').inputValue()), newDownload);
    failConnection = false; await click('保存节点参数');
    await click('节点参数');
    assert.deepEqual(JSON.parse(await page.locator('#connection-parameters-downloadSettings').inputValue()), newDownload);
    await page.locator('#connection-parameters-downloadSettings').fill('');
    const remaining = JSON.parse(new URL(await page.locator('#connection-link').inputValue()).searchParams.get('extra'));
    assert.deepEqual(remaining, {noSSEHeader:true});
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.locator('#connection-dialog').evaluate(el => el.scrollWidth <= el.clientWidth), true);
    await page.setViewportSize({width:1000,height:850});
    await click('保存节点参数');
    nodes[0].name = '法兰克福 · Reality';
    await click('刷新状态');
    fs.mkdirSync(path.join(__dirname, '.cache'), { recursive: true });
    await page.screenshot({ path: path.join(__dirname, '.cache', 'panel-desktop.png'), fullPage: true });
    await page.emulateMedia({ colorScheme: 'dark' });
    await page.waitForFunction(() => document.documentElement.classList.contains('dark'));
    await page.screenshot({ path: path.join(__dirname, '.cache', 'panel-dark.png'), fullPage: true });
    await page.emulateMedia({ colorScheme: 'light' });
    await page.waitForFunction(() => !document.documentElement.classList.contains('dark'));
    assert.equal(await page.locator('#add-node').evaluate(el => el.getBoundingClientRect().height), 32);
    assert.equal(await page.locator('.actions button').first().evaluate(el => el.getBoundingClientRect().height), 24);
    await click('连接设置');
    assert.equal(await page.locator('#node-port').evaluate(el => el.getBoundingClientRect().height), 32);
    assert.deepEqual(await page.locator('#node-lan').evaluate(el => [el.getBoundingClientRect().width, el.getBoundingClientRect().height]), [40, 20]);
    await page.screenshot({ path: path.join(__dirname, '.cache', 'panel-settings.png'), fullPage: true });
    await click('关闭连接设置');
    await page.setViewportSize({ width: 390, height: 844 });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    fs.mkdirSync(path.join(__dirname, '.cache'), { recursive: true });
    await page.screenshot({ path: path.join(__dirname, '.cache', 'panel-mobile.png'), fullPage: true });
    failDelete = true;
    await click('删除'); await click('确认删除');
    assert.equal(upstreams.length, 0);
    assert.equal(nodes.length, 1);
    assert.match(await page.locator('#notice').innerText(), /SIM 绑定已移除.*本地节点清理失败/);
    failDelete = false;
    await click('删除'); await click('确认删除');
    assert.equal(nodes.length, 0);
    await click('新增节点');
    await page.locator('#link').fill('vless://test-node');
    await page.locator('#import-port').fill('12347');
    await page.locator('#import-lan').check();
    await page.locator('#import-auth').check();
    await page.locator('#import-username').fill('import-user');
    await page.locator('#import-password').fill('import-password');
    await click('导入并推送到 VoCat');
    assert.equal(upstreams[0].addr, '127.0.0.1:12347');
    assert.equal(upstreams[0].username, 'import-user');
    assert.equal(upstreams[0].password, 'import-password');
    assert.equal(nodes[0].allow_lan, true);
    assert.equal(await page.locator('#import-password').inputValue(), '');
    assert.equal(await page.locator('#import-port').inputValue(), '');
    assert.equal(await page.locator('#import-dialog').evaluate(el => el.open), false);
    assert.equal(await page.locator('#link').inputValue(), '');
    await click('删除'); await click('确认删除');
    const beforeHTTPImport = writes;
    await click('新增节点');
    await page.locator('#link').fill('vless://http-node');
    await page.locator('#import-mode').selectOption('http');
    await click('导入并启动 HTTP 代理');
    assert.equal(nodes[0].inbound_mode, 'http');
    assert.equal(writes, beforeHTTPImport);
    assert.equal(upstreams.length, 0);
    await page.goto('http://vocat.test/host');
    const embedded = page.frameLocator('iframe');
    await embedded.getByRole('button', { name: '新增节点', exact: true }).click();
    assert.equal(await embedded.locator('#import-dialog').evaluate(el => el.open), true);
    assert.equal(await embedded.locator('html').evaluate(el => el.classList.contains('dark')), true);
    await page.evaluate(() => document.documentElement.classList.remove('dark'));
    await embedded.locator('html:not(.dark)').waitFor();
    await embedded.getByRole('button', { name: '关闭', exact: true }).click();
    assert.equal(errors.length, 0, errors.join('\n'));
    console.log('PASS browser: KCP options, XHTTP download roundtrip and invalid JSON retention, import retention, retry, CSRF, escaping, ownership, stop/start, partial deletion, mobile layout, LAN/auth settings, credential retention and update, simplified layout');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
